/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ide_conversor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author juanf
 */
public class años_perro extends javax.swing.JFrame {

    /**
     * Creates new form años_perro
     */
    public años_perro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Teclado = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        BotonInicio = new javax.swing.JButton();
        TecladoPantalla = new javax.swing.JTextField();
        Imagen1 = new javax.swing.JLabel();
        Imagen2 = new javax.swing.JLabel();
        ResultadoPantalla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Años humano-perro");
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(200, 150));
        setName("VentanaP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));

        Titulo.setBackground(new java.awt.Color(255, 255, 204));
        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 51, 51));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("CONVERSOR DE AÑOS HUMANO-PERRO");
        Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Titulo.setName("Titulo"); // NOI18N
        getContentPane().add(Titulo, java.awt.BorderLayout.PAGE_START);

        Cuerpo.setPreferredSize(new java.awt.Dimension(700, 400));

        Teclado.setBackground(new java.awt.Color(0, 0, 0));
        Teclado.setLayout(new java.awt.GridLayout(4, 3));

        boton1.setBackground(new java.awt.Color(51, 51, 255));
        boton1.setLabel("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        Teclado.add(boton1);

        boton2.setBackground(new java.awt.Color(255, 51, 51));
        boton2.setLabel("2");
        Teclado.add(boton2);

        boton3.setBackground(new java.awt.Color(255, 255, 51));
        boton3.setLabel("3");
        Teclado.add(boton3);

        boton4.setBackground(new java.awt.Color(102, 153, 0));
        boton4.setLabel("4");
        Teclado.add(boton4);

        boton5.setBackground(new java.awt.Color(255, 153, 51));
        boton5.setLabel("5");
        Teclado.add(boton5);

        boton6.setBackground(new java.awt.Color(51, 0, 204));
        boton6.setLabel("6");
        Teclado.add(boton6);

        boton7.setBackground(new java.awt.Color(255, 153, 153));
        boton7.setLabel("7");
        Teclado.add(boton7);

        boton8.setBackground(new java.awt.Color(153, 0, 0));
        boton8.setLabel("8");
        Teclado.add(boton8);

        boton9.setBackground(new java.awt.Color(204, 204, 255));
        boton9.setLabel("9");
        Teclado.add(boton9);

        boton0.setBackground(new java.awt.Color(204, 255, 204));
        boton0.setLabel("0");
        Teclado.add(boton0);

        botonMenos.setBackground(new java.awt.Color(0, 204, 204));
        botonMenos.setLabel("borrar");
        Teclado.add(botonMenos);

        BotonInicio.setBackground(new java.awt.Color(255, 51, 102));
        BotonInicio.setLabel("iniciar");
        Teclado.add(BotonInicio);

        TecladoPantalla.setEditable(false);
        TecladoPantalla.setBackground(new java.awt.Color(102, 204, 255));
        TecladoPantalla.setText("Ingrese un numero");

        Imagen1.setBackground(new java.awt.Color(102, 102, 255));
        Imagen1.setText("jLabel1");

        Imagen2.setBackground(new java.awt.Color(102, 102, 255));
        Imagen2.setText("jLabel1");

        ResultadoPantalla.setEditable(false);
        ResultadoPantalla.setBackground(new java.awt.Color(204, 204, 255));
        ResultadoPantalla.setText("Resultado");
        ResultadoPantalla.setPreferredSize(new java.awt.Dimension(115, 22));

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Teclado, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(TecladoPantalla)
                    .addComponent(ResultadoPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Imagen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Imagen2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addComponent(Imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addComponent(TecladoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ResultadoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        getContentPane().add(Cuerpo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(años_perro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(años_perro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(años_perro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(años_perro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new años_perro().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JLabel Imagen2;
    private javax.swing.JTextField ResultadoPantalla;
    private javax.swing.JPanel Teclado;
    private javax.swing.JTextField TecladoPantalla;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonMenos;
    // End of variables declaration//GEN-END:variables
}
